import Link from "next/link";
import { Building2, ChevronRight } from "lucide-react";
import { createClient, getAuthUser } from "@/lib/supabase/server";

export default async function AccountantClientsPage() {
  const supabase = await createClient();
  const { data: { user } } = await getAuthUser();
  const { data: memberships } = await supabase.from("organisation_members").select("organisation_id,created_at,organisations(id,name,company_legal_name,anaf_cif)").eq("user_id", user!.id).eq("role", "accountant").or("status.is.null,status.eq.active").order("created_at");
  return <main className="mx-auto max-w-6xl p-4 sm:p-6"><div className="mb-6"><p className="text-xs font-semibold uppercase tracking-[0.12em] text-brass">Spațiu contabil</p><h1 className="mt-1 text-2xl font-bold tracking-tight">Clienții mei</h1><p className="mt-1 text-sm text-muted-foreground">Alege firma pentru verificarea lunii și exportul datelor POS.</p></div><div className="grid gap-3 sm:grid-cols-2 xl:grid-cols-3">{(memberships ?? []).map((membership) => { const org = Array.isArray(membership.organisations) ? membership.organisations[0] : membership.organisations; if (!org) return null; return <Link key={membership.organisation_id} href={`/accountant/${membership.organisation_id}`} className="group flex min-h-32 items-center gap-4 rounded-xl border border-border bg-card p-5 transition hover:border-brass/50"><span className="flex size-11 shrink-0 items-center justify-center rounded-lg bg-accent"><Building2 className="size-5" /></span><span className="min-w-0 flex-1"><span className="block truncate font-semibold">{org.company_legal_name || org.name}</span><span className="mt-1 block text-xs text-muted-foreground">{org.anaf_cif ? `CUI ${org.anaf_cif}` : "CUI necompletat"}</span></span><ChevronRight className="size-4 text-muted-foreground transition group-hover:translate-x-0.5" /></Link>; })}</div>{!memberships?.length && <p className="rounded-xl border border-dashed p-8 text-center text-sm text-muted-foreground">Nu ai încă firme conectate.</p>}</main>;
}
