-- Dolce Nera recipe-cost import from Odoo (Abi Flowers Boutique, company_id=42)
-- Generated by scripts/extract_dolcenera_recipe_costs.py — NOT YET APPLIED.
-- Only exact-name-matched finished products with ingredients are included below.
-- Ingredient-level matches are exact-only too; unmatched ingredients are stored as ingredient_name text only (no stock link).

-- LATTE - NICARAGUA S.O. 360ml -> LATTE - NICARAGUA S.O. 360ml (3d4c2527-b1ae-4ff2-a5e4-a3abab1070cf)
WITH new_recipe AS (
  INSERT INTO recipes (organisation_id, name, product_id, yield_qty)
  VALUES ('b01ce0e0-d01c-4042-0000-000000000042', 'LATTE - NICARAGUA S.O. 360ml', '3d4c2527-b1ae-4ff2-a5e4-a3abab1070cf', 1.0)
  RETURNING id
)
INSERT INTO recipe_items (recipe_id, ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id)
SELECT new_recipe.id, v.ingredient_name, v.organisation_id, v.quantity, v.unit_of_measure, v.unit_cost, v.total_cost, v.ingredient_product_id
FROM new_recipe CROSS JOIN (VALUES
  ('CAFEA PRAJITA - NICARAGUA SHG 250gr', 'b01ce0e0-d01c-4042-0000-000000000042', 0.02, 'kg', 117.0, 2.34, '2a65698d-f4e0-450f-8270-5e862706dc19'),
  ('PAHAR 12 OZ', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.22, 0.22, '0e223cc3-b75b-4bd9-a20c-11fb8753218f'),
  ('CAPAC SL45', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.13, 0.13, '9989a447-5901-4a7c-a2f5-a38f2c5955a7'),
  ('PALETE', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.04, 0.04, 'afa8aefc-c6d5-4a7d-9a00-b75639c704f4'),
  ('ZAHAR BRUN 5 GR', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.07, 0.07, 'b05b0e00-5331-4a44-beb3-fcd092704c31'),
  ('LAPTE BIO UHT', 'b01ce0e0-d01c-4042-0000-000000000042', 0.25, 'L', 6.0, 1.5, '20c512f5-19f5-4bb7-96b3-61c176fbc3ea')
) AS v(ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id);

-- AMERICANO S.O. 230ml -> AMERICANO S.O. 230ml (81d75718-698b-48cc-86db-38d649355463)
WITH new_recipe AS (
  INSERT INTO recipes (organisation_id, name, product_id, yield_qty)
  VALUES ('b01ce0e0-d01c-4042-0000-000000000042', 'AMERICANO S.O. 230ml', '81d75718-698b-48cc-86db-38d649355463', 1.0)
  RETURNING id
)
INSERT INTO recipe_items (recipe_id, ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id)
SELECT new_recipe.id, v.ingredient_name, v.organisation_id, v.quantity, v.unit_of_measure, v.unit_cost, v.total_cost, v.ingredient_product_id
FROM new_recipe CROSS JOIN (VALUES
  ('PAHAR 8 OZ', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.2, 0.2, '8eca31f2-7187-433e-8e2b-c7724d2c311c'),
  ('CAPAC SL37', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.12, 0.12, '35565c85-4816-4683-85e3-f215b7315e75'),
  ('PALETE', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.04, 0.04, 'afa8aefc-c6d5-4a7d-9a00-b75639c704f4'),
  ('CAFEA PRAJITA - GUJI ETHIOPIA 1kg', 'b01ce0e0-d01c-4042-0000-000000000042', 0.02, 'kg', 127.0, 2.54, '5ad0c48d-754c-47a2-9268-15a28309d101'),
  ('ZAHAR BRUN 5 GR', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.07, 0.07, 'b05b0e00-5331-4a44-beb3-fcd092704c31')
) AS v(ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id);

-- DOUBLE RISTRETTO - NICARAGUA S.O. 40ml -> DOUBLE RISTRETTO - NICARAGUA S.O. 40ml (3c678a4f-648c-4c03-ab8a-3a818d93c436)
WITH new_recipe AS (
  INSERT INTO recipes (organisation_id, name, product_id, yield_qty)
  VALUES ('b01ce0e0-d01c-4042-0000-000000000042', 'DOUBLE RISTRETTO - NICARAGUA S.O. 40ml', '3c678a4f-648c-4c03-ab8a-3a818d93c436', 1.0)
  RETURNING id
)
INSERT INTO recipe_items (recipe_id, ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id)
SELECT new_recipe.id, v.ingredient_name, v.organisation_id, v.quantity, v.unit_of_measure, v.unit_cost, v.total_cost, v.ingredient_product_id
FROM new_recipe CROSS JOIN (VALUES
  ('CAFEA PRAJITA - NICARAGUA SHG 250gr', 'b01ce0e0-d01c-4042-0000-000000000042', 0.02, 'kg', 117.0, 2.34, '2a65698d-f4e0-450f-8270-5e862706dc19'),
  ('PAHAR 6 OZ', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.1, 0.1, '14ecacea-0f5b-4dee-9f98-bfb8d6e8a0a9'),
  ('CAPAC DE PLASTIC 6 OZ', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.09, 0.09, '4d14f609-4674-44b3-b11e-0c2f7e8f0e24'),
  ('PALETE', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.04, 0.04, 'afa8aefc-c6d5-4a7d-9a00-b75639c704f4'),
  ('ZAHAR BRUN 5 GR', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.07, 0.07, 'b05b0e00-5331-4a44-beb3-fcd092704c31')
) AS v(ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id);

-- DOUBLE ESPRESSO - NICARAGUA S.O. 60ml -> DOUBLE ESPRESSO - NICARAGUA S.O. 60ml (3ea1427f-d150-4b70-a979-e31798ddfb7e)
WITH new_recipe AS (
  INSERT INTO recipes (organisation_id, name, product_id, yield_qty)
  VALUES ('b01ce0e0-d01c-4042-0000-000000000042', 'DOUBLE ESPRESSO - NICARAGUA S.O. 60ml', '3ea1427f-d150-4b70-a979-e31798ddfb7e', 1.0)
  RETURNING id
)
INSERT INTO recipe_items (recipe_id, ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id)
SELECT new_recipe.id, v.ingredient_name, v.organisation_id, v.quantity, v.unit_of_measure, v.unit_cost, v.total_cost, v.ingredient_product_id
FROM new_recipe CROSS JOIN (VALUES
  ('CAPAC DE PLASTIC 6 OZ', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.09, 0.09, '4d14f609-4674-44b3-b11e-0c2f7e8f0e24'),
  ('PALETE', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.04, 0.04, 'afa8aefc-c6d5-4a7d-9a00-b75639c704f4'),
  ('ZAHAR BRUN 5 GR', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.07, 0.07, 'b05b0e00-5331-4a44-beb3-fcd092704c31'),
  ('CAFEA PRAJITA - NICARAGUA SHG 250gr', 'b01ce0e0-d01c-4042-0000-000000000042', 0.02, 'kg', 117.0, 2.34, '2a65698d-f4e0-450f-8270-5e862706dc19'),
  ('PAHAR 6 OZ', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.1, 0.1, '14ecacea-0f5b-4dee-9f98-bfb8d6e8a0a9')
) AS v(ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id);

-- DOUBLE MACCHIATO - NICARAGUA S.O. 80ml -> DOUBLE MACCHIATO - NICARAGUA S.O. 80ml (cc224911-73c0-4d6e-a49a-5350f5b361cf)
WITH new_recipe AS (
  INSERT INTO recipes (organisation_id, name, product_id, yield_qty)
  VALUES ('b01ce0e0-d01c-4042-0000-000000000042', 'DOUBLE MACCHIATO - NICARAGUA S.O. 80ml', 'cc224911-73c0-4d6e-a49a-5350f5b361cf', 1.0)
  RETURNING id
)
INSERT INTO recipe_items (recipe_id, ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id)
SELECT new_recipe.id, v.ingredient_name, v.organisation_id, v.quantity, v.unit_of_measure, v.unit_cost, v.total_cost, v.ingredient_product_id
FROM new_recipe CROSS JOIN (VALUES
  ('CAFEA PRAJITA - NICARAGUA SHG 250gr', 'b01ce0e0-d01c-4042-0000-000000000042', 0.02, 'kg', 117.0, 2.34, '2a65698d-f4e0-450f-8270-5e862706dc19'),
  ('PAHAR 6 OZ', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.1, 0.1, '14ecacea-0f5b-4dee-9f98-bfb8d6e8a0a9'),
  ('CAPAC DE PLASTIC 6 OZ', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.09, 0.09, '4d14f609-4674-44b3-b11e-0c2f7e8f0e24'),
  ('PALETE', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.04, 0.04, 'afa8aefc-c6d5-4a7d-9a00-b75639c704f4'),
  ('ZAHAR BRUN 5 GR', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.07, 0.07, 'b05b0e00-5331-4a44-beb3-fcd092704c31'),
  ('LAPTE BIO UHT', 'b01ce0e0-d01c-4042-0000-000000000042', 0.04, 'L', 6.0, 0.24, '20c512f5-19f5-4bb7-96b3-61c176fbc3ea')
) AS v(ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id);

-- FLAT WHITE - NICARAGUA S.O. 240ml -> FLAT WHITE - NICARAGUA S.O. 240ml (d02872ab-37dd-4473-87b6-6fffa3c1d1bb)
WITH new_recipe AS (
  INSERT INTO recipes (organisation_id, name, product_id, yield_qty)
  VALUES ('b01ce0e0-d01c-4042-0000-000000000042', 'FLAT WHITE - NICARAGUA S.O. 240ml', 'd02872ab-37dd-4473-87b6-6fffa3c1d1bb', 1.0)
  RETURNING id
)
INSERT INTO recipe_items (recipe_id, ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id)
SELECT new_recipe.id, v.ingredient_name, v.organisation_id, v.quantity, v.unit_of_measure, v.unit_cost, v.total_cost, v.ingredient_product_id
FROM new_recipe CROSS JOIN (VALUES
  ('CAFEA PRAJITA - NICARAGUA SHG 250gr', 'b01ce0e0-d01c-4042-0000-000000000042', 0.02, 'kg', 117.0, 2.34, '2a65698d-f4e0-450f-8270-5e862706dc19'),
  ('LAPTE BIO UHT', 'b01ce0e0-d01c-4042-0000-000000000042', 0.15, 'L', 6.0, 0.9, '20c512f5-19f5-4bb7-96b3-61c176fbc3ea'),
  ('PAHAR 8 OZ', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.2, 0.2, '8eca31f2-7187-433e-8e2b-c7724d2c311c'),
  ('CAPAC SL37', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.12, 0.12, '35565c85-4816-4683-85e3-f215b7315e75'),
  ('PALETE', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.04, 0.04, 'afa8aefc-c6d5-4a7d-9a00-b75639c704f4'),
  ('ZAHAR BRUN 5 GR', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.07, 0.07, 'b05b0e00-5331-4a44-beb3-fcd092704c31')
) AS v(ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id);

-- AMERICANO - NICARAGUA S.O. 360ml -> AMERICANO - NICARAGUA S.O. 360ml (7cc32b1a-0d1f-4534-8f1a-08c8268f8b45)
WITH new_recipe AS (
  INSERT INTO recipes (organisation_id, name, product_id, yield_qty)
  VALUES ('b01ce0e0-d01c-4042-0000-000000000042', 'AMERICANO - NICARAGUA S.O. 360ml', '7cc32b1a-0d1f-4534-8f1a-08c8268f8b45', 1.0)
  RETURNING id
)
INSERT INTO recipe_items (recipe_id, ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id)
SELECT new_recipe.id, v.ingredient_name, v.organisation_id, v.quantity, v.unit_of_measure, v.unit_cost, v.total_cost, v.ingredient_product_id
FROM new_recipe CROSS JOIN (VALUES
  ('CAFEA PRAJITA - NICARAGUA SHG 250gr', 'b01ce0e0-d01c-4042-0000-000000000042', 0.02, 'kg', 117.0, 2.34, '2a65698d-f4e0-450f-8270-5e862706dc19'),
  ('PAHAR 12 OZ', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.22, 0.22, '0e223cc3-b75b-4bd9-a20c-11fb8753218f'),
  ('PALETE', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.04, 0.04, 'afa8aefc-c6d5-4a7d-9a00-b75639c704f4'),
  ('ZAHAR BRUN 5 GR', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.07, 0.07, 'b05b0e00-5331-4a44-beb3-fcd092704c31'),
  ('CAPAC SL45', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.13, 0.13, '9989a447-5901-4a7c-a2f5-a38f2c5955a7')
) AS v(ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id);

-- BABYCCINNO 240ml -> BABYCCINNO 240ml (d64000ec-2dab-449c-99a9-6edd86b766be)
WITH new_recipe AS (
  INSERT INTO recipes (organisation_id, name, product_id, yield_qty)
  VALUES ('b01ce0e0-d01c-4042-0000-000000000042', 'BABYCCINNO 240ml', 'd64000ec-2dab-449c-99a9-6edd86b766be', 1.0)
  RETURNING id
)
INSERT INTO recipe_items (recipe_id, ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id)
SELECT new_recipe.id, v.ingredient_name, v.organisation_id, v.quantity, v.unit_of_measure, v.unit_cost, v.total_cost, v.ingredient_product_id
FROM new_recipe CROSS JOIN (VALUES
  ('PAHAR 8 OZ', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.2, 0.2, '8eca31f2-7187-433e-8e2b-c7724d2c311c'),
  ('LAPTE BIO UHT', 'b01ce0e0-d01c-4042-0000-000000000042', 0.02, 'L', 6.0, 0.12, '20c512f5-19f5-4bb7-96b3-61c176fbc3ea'),
  ('WHITE CHOCOLATE GOURMET WHITE VANILA', 'b01ce0e0-d01c-4042-0000-000000000042', 0.01, 'kg', 50.0, 0.5, '19ca7c72-07f0-48a0-9727-e24a637178b0'),
  ('PAIE', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.06, 0.06, 'ff4d2154-45be-4940-8f8d-d96508611a1d')
) AS v(ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id);

-- DOUBLE ESPRESSO - PREMIUM 10 - 60ml -> DOUBLE ESPRESSO - PREMIUM 10 - 60ml (96dc61a8-4f4b-4459-8092-89416a11540a)
WITH new_recipe AS (
  INSERT INTO recipes (organisation_id, name, product_id, yield_qty)
  VALUES ('b01ce0e0-d01c-4042-0000-000000000042', 'DOUBLE ESPRESSO - PREMIUM 10 - 60ml', '96dc61a8-4f4b-4459-8092-89416a11540a', 1.0)
  RETURNING id
)
INSERT INTO recipe_items (recipe_id, ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id)
SELECT new_recipe.id, v.ingredient_name, v.organisation_id, v.quantity, v.unit_of_measure, v.unit_cost, v.total_cost, v.ingredient_product_id
FROM new_recipe CROSS JOIN (VALUES
  ('CAPAC DE PLASTIC 6 OZ', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.09, 0.09, '4d14f609-4674-44b3-b11e-0c2f7e8f0e24'),
  ('CAFEA PRAJITA - PREMIUM 10 250gr', 'b01ce0e0-d01c-4042-0000-000000000042', 0.02, 'kg', 124.32, 2.4864, '06497e03-22fb-4712-b778-11e26bbd8d07'),
  ('PAHAR 6 OZ', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.1, 0.1, '14ecacea-0f5b-4dee-9f98-bfb8d6e8a0a9')
) AS v(ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id);

-- FRESH PORTOCALE -> FRESH PORTOCALE (38c84dd4-fc1a-4bae-8786-302e60f87cdb)
WITH new_recipe AS (
  INSERT INTO recipes (organisation_id, name, product_id, yield_qty)
  VALUES ('b01ce0e0-d01c-4042-0000-000000000042', 'FRESH PORTOCALE', '38c84dd4-fc1a-4bae-8786-302e60f87cdb', 1.0)
  RETURNING id
)
INSERT INTO recipe_items (recipe_id, ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id)
SELECT new_recipe.id, v.ingredient_name, v.organisation_id, v.quantity, v.unit_of_measure, v.unit_cost, v.total_cost, v.ingredient_product_id
FROM new_recipe CROSS JOIN (VALUES
  ('PORTOCALE', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'kg', 5.0, 5.0, '25ecc230-496d-4409-94bc-47ea9cf5a5bf'),
  ('CAPAC PAHAR FRAPPE DL95', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.15, 0.15, '2f18bad9-0696-40c4-84a5-60b4f1c8ecca'),
  ('CAPAC PAHAR FRAPPE DL95', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.15, 0.15, '2f18bad9-0696-40c4-84a5-60b4f1c8ecca'),
  ('PAIE', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.06, 0.06, 'ff4d2154-45be-4940-8f8d-d96508611a1d')
) AS v(ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id);

-- CAPPUCCINO - NICARAGUA S.O. 360ml -> CAPPUCCINO - NICARAGUA S.O. 360ml (c46afbb7-d6a2-424a-bcf2-28c48a85c5e8)
WITH new_recipe AS (
  INSERT INTO recipes (organisation_id, name, product_id, yield_qty)
  VALUES ('b01ce0e0-d01c-4042-0000-000000000042', 'CAPPUCCINO - NICARAGUA S.O. 360ml', 'c46afbb7-d6a2-424a-bcf2-28c48a85c5e8', 1.0)
  RETURNING id
)
INSERT INTO recipe_items (recipe_id, ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id)
SELECT new_recipe.id, v.ingredient_name, v.organisation_id, v.quantity, v.unit_of_measure, v.unit_cost, v.total_cost, v.ingredient_product_id
FROM new_recipe CROSS JOIN (VALUES
  ('LAPTE BIO UHT', 'b01ce0e0-d01c-4042-0000-000000000042', 0.25, 'L', 6.0, 1.5, '20c512f5-19f5-4bb7-96b3-61c176fbc3ea'),
  ('CAFEA PRAJITA - NICARAGUA SHG 250gr', 'b01ce0e0-d01c-4042-0000-000000000042', 0.02, 'kg', 117.0, 2.34, '2a65698d-f4e0-450f-8270-5e862706dc19'),
  ('PAHAR 12 OZ', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.22, 0.22, '0e223cc3-b75b-4bd9-a20c-11fb8753218f'),
  ('CAPAC SL45', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.13, 0.13, '9989a447-5901-4a7c-a2f5-a38f2c5955a7'),
  ('PALETE', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.04, 0.04, 'afa8aefc-c6d5-4a7d-9a00-b75639c704f4'),
  ('ZAHAR BRUN 5 GR', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.07, 0.07, 'b05b0e00-5331-4a44-beb3-fcd092704c31')
) AS v(ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id);

-- FRESH MIXT -> FRESH MIXT (95151651-d4ac-438c-930e-02ee582e3d35)
WITH new_recipe AS (
  INSERT INTO recipes (organisation_id, name, product_id, yield_qty)
  VALUES ('b01ce0e0-d01c-4042-0000-000000000042', 'FRESH MIXT', '95151651-d4ac-438c-930e-02ee582e3d35', 1.0)
  RETURNING id
)
INSERT INTO recipe_items (recipe_id, ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id)
SELECT new_recipe.id, v.ingredient_name, v.organisation_id, v.quantity, v.unit_of_measure, v.unit_cost, v.total_cost, v.ingredient_product_id
FROM new_recipe CROSS JOIN (VALUES
  ('PAHAR FRAPPE DOLCE NERA 3CNEW', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.38, 0.38, 'fba7aed5-34db-4d36-95ec-fbefbffccc98'),
  ('CAPAC PAHAR FRAPPE DL95', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.15, 0.15, '2f18bad9-0696-40c4-84a5-60b4f1c8ecca'),
  ('PAIE', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.06, 0.06, 'ff4d2154-45be-4940-8f8d-d96508611a1d'),
  ('GRAPEFRUIT ROSU ', 'b01ce0e0-d01c-4042-0000-000000000042', 0.35, 'kg', 6.8, 2.38, '2044d514-0d0a-4438-96fc-49f62cc95f79'),
  ('PORTOCALE', 'b01ce0e0-d01c-4042-0000-000000000042', 0.2, 'kg', 5.0, 1.0, '25ecc230-496d-4409-94bc-47ea9cf5a5bf'),
  ('RODII', 'b01ce0e0-d01c-4042-0000-000000000042', 0.3, 'kg', 13.0, 3.9, 'a0e2debc-9c4f-4b4a-b9b4-0b63e103effb'),
  ('LAMAIE ', 'b01ce0e0-d01c-4042-0000-000000000042', 0.15, 'kg', 10.3, 1.545, 'ca2611fa-ce89-4690-b0e6-8cd6ed92e29e')
) AS v(ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id);

-- FRESH RODII -> FRESH RODII (12bf1683-3895-41e3-907b-31fe9fa7798d)
WITH new_recipe AS (
  INSERT INTO recipes (organisation_id, name, product_id, yield_qty)
  VALUES ('b01ce0e0-d01c-4042-0000-000000000042', 'FRESH RODII', '12bf1683-3895-41e3-907b-31fe9fa7798d', 1.0)
  RETURNING id
)
INSERT INTO recipe_items (recipe_id, ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id)
SELECT new_recipe.id, v.ingredient_name, v.organisation_id, v.quantity, v.unit_of_measure, v.unit_cost, v.total_cost, v.ingredient_product_id
FROM new_recipe CROSS JOIN (VALUES
  ('RODII', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'kg', 13.0, 13.0, 'a0e2debc-9c4f-4b4a-b9b4-0b63e103effb'),
  ('PAHAR FRAPPE DOLCE NERA 3CNEW', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.38, 0.38, 'fba7aed5-34db-4d36-95ec-fbefbffccc98'),
  ('CAPAC PAHAR FRAPPE DL95', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.15, 0.15, '2f18bad9-0696-40c4-84a5-60b4f1c8ecca'),
  ('PAIE', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.06, 0.06, 'ff4d2154-45be-4940-8f8d-d96508611a1d')
) AS v(ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id);

-- FRESH GRAPEFRUIT -> FRESH GRAPEFRUIT (1174fdee-91e7-46b8-95d3-c7055476f367)
WITH new_recipe AS (
  INSERT INTO recipes (organisation_id, name, product_id, yield_qty)
  VALUES ('b01ce0e0-d01c-4042-0000-000000000042', 'FRESH GRAPEFRUIT', '1174fdee-91e7-46b8-95d3-c7055476f367', 1.0)
  RETURNING id
)
INSERT INTO recipe_items (recipe_id, ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id)
SELECT new_recipe.id, v.ingredient_name, v.organisation_id, v.quantity, v.unit_of_measure, v.unit_cost, v.total_cost, v.ingredient_product_id
FROM new_recipe CROSS JOIN (VALUES
  ('GRAPEFRUIT ROSU ', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'kg', 6.8, 6.8, '2044d514-0d0a-4438-96fc-49f62cc95f79'),
  ('CAPAC PAHAR FRAPPE DL95', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.15, 0.15, '2f18bad9-0696-40c4-84a5-60b4f1c8ecca'),
  ('PAHAR FRAPPE DOLCE NERA 3CNEW', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.38, 0.38, 'fba7aed5-34db-4d36-95ec-fbefbffccc98'),
  ('PAIE', 'b01ce0e0-d01c-4042-0000-000000000042', 1.0, 'Units', 0.06, 0.06, 'ff4d2154-45be-4940-8f8d-d96508611a1d')
) AS v(ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id);

