#!/usr/bin/env python3
"""Extract finished-product recipe costs from the old Odoo (Abi Flowers Boutique,
company_id=42, db dolcenera_20260615) and match them against the franchisetech
'Dolce Nera - CoffeeShop' org's existing products.

READ-ONLY against Odoo. Produces a gap report + a not-yet-applied SQL file for
recipes/recipe_items — nothing is written to Supabase by this script.

Requires data/dolcenera-supabase-products-snapshot.json, exported from Supabase via:

    select p.id, p.name, p.unit_of_measure, p.cost_price, p.sale_price,
           (select count(*) from recipes r where r.product_id = p.id) as existing_recipe_count
    from products p
    where p.organisation_id = 'b01ce0e0-d01c-4042-0000-000000000042'
    order by p.name;

against project ycqzxlahhfqwuteistvf (fridgeproof), saved as a JSON array.
"""
from __future__ import annotations

import csv
import json
import re
import subprocess
import unicodedata
from pathlib import Path

ORG_ID = "b01ce0e0-d01c-4042-0000-000000000042"
ODOO_COMPANY = 42
ODOO_DB = "dolcenera_20260615"


def norm(s: str) -> str:
    s = unicodedata.normalize("NFKD", s or "")
    s = "".join(c for c in s if not unicodedata.combining(c))
    return re.sub(r"[^a-z0-9]+", "", s.lower())


def sql_str(s: str) -> str:
    return "'" + (s or "").replace("'", "''") + "'"


def psql_json(query: str) -> list[dict]:
    raw = subprocess.check_output(
        ["psql", "-d", ODOO_DB, "-t", "-A", "-c", query],
        text=True,
    ).strip()
    if not raw:
        return []
    return json.loads(raw)


BOM_QUERY = f"""
SELECT json_agg(row_to_json(t)) FROM (
  SELECT
    b.id AS bom_id,
    COALESCE(NULLIF(pt.name->>'ro_RO',''), pt.name->>'en_US', pt.name::text) AS finished_product,
    b.product_qty AS yield_qty
  FROM mrp_bom b
  JOIN product_template pt ON pt.id = b.product_tmpl_id
  WHERE b.company_id = {ODOO_COMPANY} AND b.active = true
) t;
"""

BOM_LINE_QUERY = f"""
SELECT json_agg(row_to_json(t)) FROM (
  SELECT
    bl.bom_id,
    bl.product_qty AS ingredient_qty,
    COALESCE(NULLIF(ipt.name->>'ro_RO',''), ipt.name->>'en_US', ipt.name::text) AS ingredient_name,
    iuom.name->>'en_US' AS ingredient_uom,
    bl.product_id AS ingredient_product_id,
    (
      SELECT svl.unit_cost FROM stock_valuation_layer svl
      WHERE svl.product_id = bl.product_id AND svl.company_id = {ODOO_COMPANY}
      ORDER BY svl.create_date DESC LIMIT 1
    ) AS valuation_unit_cost,
    (
      SELECT ip.value_float FROM ir_property ip
      WHERE ip.name = 'standard_price' AND ip.company_id = {ODOO_COMPANY}
        AND ip.res_id = 'product.product,' || bl.product_id::text
      LIMIT 1
    ) AS standard_price_cost
  FROM mrp_bom_line bl
  JOIN product_product ipp ON ipp.id = bl.product_id
  JOIN product_template ipt ON ipt.id = ipp.product_tmpl_id
  LEFT JOIN uom_uom iuom ON iuom.id = bl.product_uom_id
  JOIN mrp_bom b ON b.id = bl.bom_id
  WHERE b.company_id = {ODOO_COMPANY} AND b.active = true
) t;
"""


def main() -> None:
    repo_root = Path(__file__).resolve().parents[1]
    out_dir = repo_root / "data"
    out_dir.mkdir(parents=True, exist_ok=True)

    snapshot_path = out_dir / "dolcenera-supabase-products-snapshot.json"
    if not snapshot_path.exists():
        raise SystemExit(f"Missing {snapshot_path} — export it from Supabase first (see module docstring).")
    supa_products = json.loads(snapshot_path.read_text())
    supa_by_norm: dict[str, dict] = {}
    for p in supa_products:
        supa_by_norm.setdefault(norm(p["name"]), p)

    def resolve_match(name: str) -> dict | None:
        n = norm(name)
        if not n:
            return None
        if n in supa_by_norm:
            return {"product": supa_by_norm[n], "confidence": "exact"}
        candidates = [p for k, p in supa_by_norm.items() if k and (k in n or n in k)]
        if len(candidates) == 1:
            return {"product": candidates[0], "confidence": "fuzzy"}
        return None

    boms = psql_json(BOM_QUERY)
    lines = psql_json(BOM_LINE_QUERY)

    lines_by_bom: dict[int, list[dict]] = {}
    for ln in lines:
        lines_by_bom.setdefault(ln["bom_id"], []).append(ln)

    def ingredient_cost(ln: dict) -> float:
        if ln.get("valuation_unit_cost") is not None:
            return float(ln["valuation_unit_cost"])
        if ln.get("standard_price_cost") is not None:
            return float(ln["standard_price_cost"])
        return 0.0

    report_rows = []
    sql_statements: list[str] = [
        "-- Dolce Nera recipe-cost import from Odoo (Abi Flowers Boutique, company_id=42)",
        "-- Generated by scripts/extract_dolcenera_recipe_costs.py — NOT YET APPLIED.",
        "-- Only exact-name-matched finished products with ingredients are included below.",
        "-- Ingredient-level matches are exact-only too; unmatched ingredients are stored as ingredient_name text only (no stock link).",
        "",
    ]

    finished_matched = finished_fuzzy = finished_unmatched = no_ingredients = 0

    for bom in boms:
        bom_id = bom["bom_id"]
        finished_name = bom["finished_product"]
        yield_qty = float(bom.get("yield_qty") or 1) or 1
        bom_lines = lines_by_bom.get(bom_id, [])

        total_cost = sum(ingredient_cost(ln) * float(ln["ingredient_qty"]) for ln in bom_lines)
        cost_per_unit = total_cost / yield_qty if yield_qty else 0.0

        match = resolve_match(finished_name)
        status = "unmatched"
        matched_id = matched_name = ""
        existing_recipes = 0
        if match:
            status = match["confidence"]
            matched_id = match["product"]["id"]
            matched_name = match["product"]["name"]
            existing_recipes = match["product"].get("existing_recipe_count") or 0
            if status == "exact":
                if existing_recipes:
                    status = "exact_has_existing_recipe"
                finished_matched += 1
            else:
                finished_fuzzy += 1
        else:
            finished_unmatched += 1

        if not bom_lines:
            no_ingredients += 1

        report_rows.append({
            "odoo_finished_product": finished_name,
            "odoo_bom_id": bom_id,
            "ingredient_count": len(bom_lines),
            "computed_cost_per_unit": round(cost_per_unit, 4),
            "match_status": status,
            "franchisetech_product_id": matched_id,
            "franchisetech_product_name": matched_name,
            "existing_recipe_rows": existing_recipes,
        })

        # Skip SQL generation for anything not a clean, recipe-free exact match —
        # those need a human decision (overwrite vs. skip vs. merge), not a silent insert.
        if status != "exact" or not bom_lines:
            continue

        value_rows = []
        for ln in bom_lines:
            ing_match = resolve_match(ln["ingredient_name"] or "")
            ing_product_id = ing_match["product"]["id"] if ing_match and ing_match["confidence"] == "exact" else None
            qty = float(ln["ingredient_qty"])
            unit_cost = round(ingredient_cost(ln), 4)
            total = round(qty * unit_cost, 4)
            value_rows.append(
                "({name}, {org}, {qty}, {uom}, {unit_cost}, {total}, {ing_id})".format(
                    name=sql_str(ln["ingredient_name"] or ""),
                    org=sql_str(ORG_ID),
                    qty=qty,
                    uom=sql_str(ln.get("ingredient_uom") or "unit"),
                    unit_cost=unit_cost,
                    total=total,
                    ing_id=sql_str(ing_product_id) if ing_product_id else "NULL",
                )
            )

        sql_statements.append(f"-- {finished_name} -> {matched_name} ({matched_id})")
        sql_statements.append(
            "WITH new_recipe AS (\n"
            "  INSERT INTO recipes (organisation_id, name, product_id, yield_qty)\n"
            f"  VALUES ({sql_str(ORG_ID)}, {sql_str(finished_name)}, {sql_str(matched_id)}, {yield_qty})\n"
            "  RETURNING id\n"
            ")\n"
            "INSERT INTO recipe_items (recipe_id, ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id)\n"
            "SELECT new_recipe.id, v.ingredient_name, v.organisation_id, v.quantity, v.unit_of_measure, v.unit_cost, v.total_cost, v.ingredient_product_id\n"
            "FROM new_recipe CROSS JOIN (VALUES\n  "
            + ",\n  ".join(value_rows)
            + "\n) AS v(ingredient_name, organisation_id, quantity, unit_of_measure, unit_cost, total_cost, ingredient_product_id);\n"
        )

    csv_path = out_dir / "dolcenera-recipe-cost-gap-report.csv"
    with csv_path.open("w", newline="", encoding="utf-8") as f:
        writer = csv.DictWriter(f, fieldnames=list(report_rows[0].keys()) if report_rows else [])
        writer.writeheader()
        writer.writerows(report_rows)

    sql_path = out_dir / "dolcenera-recipe-import.sql"
    sql_path.write_text("\n".join(sql_statements) + "\n")

    ready_for_sql = sum(1 for r in report_rows if r["match_status"] == "exact")
    has_existing = sum(1 for r in report_rows if r["match_status"] == "exact_has_existing_recipe")

    print(f"BOMs found (company {ODOO_COMPANY}): {len(boms)}")
    print(f"  clean exact matches (in generated SQL): {ready_for_sql}")
    print(f"  exact match but already has a recipe:   {has_existing} (skipped — needs your call)")
    print(f"  fuzzy matches (needs confirmation):      {finished_fuzzy}")
    print(f"  unmatched (no franchisetech product):    {finished_unmatched}")
    print(f"  BOMs without ingredient lines:           {no_ingredients}")
    print(f"Wrote {csv_path}")
    print(f"Wrote {sql_path} (NOT applied — review before running)")


if __name__ == "__main__":
    main()
