-- Isolated E2E environment only. Deliberately excludes legacy HACCP,
-- assets, sensors, reminders, calibration, and audit-log modules.
create extension if not exists pgcrypto;

create table public.profiles (id uuid primary key references auth.users(id) on delete cascade, full_name text, email text, locale text default 'ro', created_at timestamptz default now());
create table public.organisations (
  id uuid primary key default gen_random_uuid(), name text not null, business_type text, country text default 'Romania', country_code text default 'RO', currency_code text default 'RON', currency_symbol text default 'lei',
  anaf_vat_registered boolean default false, anaf_cif text, company_address text, onboarding_completed boolean default false, trial_ends_at timestamptz default (now() + interval '15 days'),
  inventory_enabled boolean default true, recipe_costing_enabled boolean default true, team_advanced_enabled boolean default false, multi_site_ops_enabled boolean default false, created_at timestamptz default now()
);
create table public.organisation_members (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, user_id uuid not null references public.profiles(id) on delete cascade, role text not null default 'owner', status text default 'active', created_at timestamptz default now(), unique(organisation_id,user_id));
create table public.sites (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, name text not null, address text, city text, created_at timestamptz default now());
create table public.product_categories (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, name text not null, color text, sort_order int default 0, category_type text default 'both', active boolean default true);
create table public.units_of_measure (id uuid primary key default gen_random_uuid(), organisation_id uuid references public.organisations(id) on delete cascade, name text not null, abbreviation text, type text, active boolean default true);
create table public.vat_rates (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, name text not null, rate numeric not null, is_default boolean default false, active boolean default true, fiscalnet_vat_group int, sort_order int default 0);
create table public.payment_methods (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, name text not null, type text not null default 'cash', active boolean default true);
create table public.products (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, category_id uuid references public.product_categories(id) on delete set null, name text not null, sale_price numeric not null default 0, cost_price numeric default 0, vat_rate numeric default 0, unit_of_measure text default 'each', active boolean default true, available_in_pos boolean default true, is_purchaseable boolean default true, is_ingredient boolean default false, current_stock_qty numeric default 0, reorder_level numeric default 0, item_type text default 'finished_product', pos_sort_order int default 0, created_at timestamptz default now());
create table public.pos_sessions (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, site_id uuid references public.sites(id), opened_by uuid references public.profiles(id), opened_at timestamptz default now(), opening_cash numeric default 0, expected_cash numeric default 0, counted_cash numeric, cash_difference numeric, status text default 'open');
create table public.pos_transactions (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, site_id uuid references public.sites(id), session_id uuid references public.pos_sessions(id), transaction_number text not null, sold_by uuid references public.profiles(id), sold_at timestamptz default now(), subtotal numeric default 0, subtotal_net numeric default 0, tax_total numeric default 0, total numeric default 0, status text default 'completed', idempotency_key text, created_at timestamptz default now());
create table public.pos_transaction_items (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, transaction_id uuid not null references public.pos_transactions(id) on delete cascade, product_id uuid references public.products(id), product_name text not null, quantity numeric not null, unit_price numeric not null, vat_rate numeric default 0, net_amount numeric default 0, vat_amount numeric default 0, gross_amount numeric default 0);
create table public.pos_cash_movements (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, session_id uuid not null references public.pos_sessions(id), movement_type text not null, amount numeric not null, reason text, performed_by uuid references public.profiles(id), performed_at timestamptz default now());
create table public.pos_daily_close (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, session_id uuid not null references public.pos_sessions(id), report_date date default current_date, expected_cash numeric default 0, counted_cash numeric default 0, cash_difference numeric default 0, closed_by uuid references public.profiles(id), closed_at timestamptz default now());
create table public.purchases (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, purchase_date date default current_date, nir_date date, invoice_number text, total_amount numeric default 0, subtotal_amount numeric default 0, tax_total numeric default 0, status text default 'draft', nir_number text, posted_at timestamptz, posted_by uuid references public.profiles(id), created_by uuid references public.profiles(id));
create table public.purchase_items (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, purchase_id uuid not null references public.purchases(id) on delete cascade, product_id uuid references public.products(id), product_name text, item_name text, quantity numeric not null, received_quantity numeric, unit_cost numeric not null, total_cost numeric not null, tax_rate numeric default 0, tax_amount numeric default 0, unit_of_measure text default 'each');
create table public.stock_movements (id uuid primary key default gen_random_uuid(), organisation_id uuid not null references public.organisations(id) on delete cascade, product_id uuid not null references public.products(id), movement_type text not null, quantity_change numeric not null, unit_cost numeric, unit_of_measure text default 'each', reference_id uuid, reference_type text, performed_by uuid references public.profiles(id), performed_at timestamptz default now());
create table public.billing_subscriptions (id uuid primary key default gen_random_uuid(), organisation_id uuid references public.organisations(id) on delete cascade, plan text, status text, current_period_end timestamptz, grace_period_ends_at timestamptz, created_at timestamptz default now());

create or replace function public.handle_new_user() returns trigger language plpgsql security definer set search_path=public as $$ begin insert into public.profiles(id,email,full_name) values(new.id,new.email,coalesce(new.raw_user_meta_data->>'full_name','')) on conflict(id) do nothing; return new; end; $$;
create trigger on_auth_user_created after insert on auth.users for each row execute procedure public.handle_new_user();
create or replace function public.is_org_member(p_org uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.organisation_members where organisation_id=p_org and user_id=auth.uid() and coalesce(status,'active')='active') $$;
create or replace function public.is_org_owner_or_manager(p_org uuid) returns boolean language sql stable security definer set search_path=public as $$ select exists(select 1 from public.organisation_members where organisation_id=p_org and user_id=auth.uid() and role in ('owner','manager') and coalesce(status,'active')='active') $$;
create or replace function public.create_organisation_with_owner(p_org_name text, p_business_type text default null, p_asset_name text default null, p_asset_type text default null) returns table(organisation_id uuid, site_id uuid) language plpgsql security definer set search_path=public as $$ declare v_user uuid:=auth.uid(); begin if v_user is null then raise exception 'AUTH_REQUIRED'; end if; insert into public.profiles(id,email) select id,email from auth.users where id=v_user on conflict(id) do nothing; insert into public.organisations(name,business_type) values(trim(p_org_name),p_business_type) returning id into organisation_id; insert into public.organisation_members(organisation_id,user_id,role) values(organisation_id,v_user,'owner'); insert into public.sites(organisation_id,name) values(organisation_id,'Locația principală') returning id into site_id; return next; end; $$;
alter table public.profiles enable row level security;
create policy profile_self on public.profiles for all to authenticated using (id=auth.uid()) with check (id=auth.uid());
alter table public.organisations enable row level security;
create policy organisation_member_access on public.organisations for all to authenticated using (public.is_org_member(id)) with check (public.is_org_member(id));
do $$ declare t text; begin foreach t in array array['organisation_members','sites','product_categories','units_of_measure','vat_rates','payment_methods','products','pos_sessions','pos_transactions','pos_transaction_items','pos_cash_movements','pos_daily_close','purchases','purchase_items','stock_movements','billing_subscriptions'] loop execute format('alter table public.%I enable row level security',t); execute format('create policy member_access on public.%I for all to authenticated using (public.is_org_member(organisation_id)) with check (public.is_org_member(organisation_id))',t); end loop; end $$;
