-- Additive indexes for unindexed FKs on hot-path tables
CREATE INDEX IF NOT EXISTS idx_cash_drawer_events_user_id_fk ON public.cash_drawer_events (user_id);
CREATE INDEX IF NOT EXISTS idx_delivery_product_mappings_product_id_fk ON public.delivery_product_mappings (product_id);
CREATE INDEX IF NOT EXISTS idx_fiscal_command_log_performed_by_fk ON public.fiscal_command_log (performed_by);
CREATE INDEX IF NOT EXISTS idx_kitchen_order_items_product_id_fk ON public.kitchen_order_items (product_id);
CREATE INDEX IF NOT EXISTS idx_kitchen_order_items_sale_item_id_fk ON public.kitchen_order_items (sale_item_id);
CREATE INDEX IF NOT EXISTS idx_kitchen_orders_site_org_fk ON public.kitchen_orders (site_id, organisation_id);
CREATE INDEX IF NOT EXISTS idx_loyalty_redemptions_customer_id_fk ON public.loyalty_redemptions (customer_id);
CREATE INDEX IF NOT EXISTS idx_loyalty_redemptions_redeemed_by_fk ON public.loyalty_redemptions (redeemed_by);
CREATE INDEX IF NOT EXISTS idx_loyalty_redemptions_transaction_id_fk ON public.loyalty_redemptions (transaction_id);
CREATE INDEX IF NOT EXISTS idx_pos_cash_movements_site_org_fk ON public.pos_cash_movements (site_id, organisation_id);
CREATE INDEX IF NOT EXISTS idx_pos_sessions_site_org_fk ON public.pos_sessions (site_id, organisation_id);
CREATE INDEX IF NOT EXISTS idx_pos_transaction_items_product_id_fk ON public.pos_transaction_items (product_id);
CREATE INDEX IF NOT EXISTS idx_pos_transaction_items_site_org_fk ON public.pos_transaction_items (site_id, organisation_id);
CREATE INDEX IF NOT EXISTS idx_pos_transaction_items_transaction_id_fk ON public.pos_transaction_items (transaction_id);
CREATE INDEX IF NOT EXISTS idx_pos_transactions_payment_method_id_fk ON public.pos_transactions (payment_method_id);
CREATE INDEX IF NOT EXISTS idx_pos_transactions_site_org_fk ON public.pos_transactions (site_id, organisation_id);
CREATE INDEX IF NOT EXISTS idx_pos_transactions_sold_by_fk ON public.pos_transactions (sold_by);
CREATE INDEX IF NOT EXISTS idx_pos_transactions_customer_id_fk ON public.pos_transactions (customer_id);
CREATE INDEX IF NOT EXISTS idx_products_category_id_fk ON public.products (category_id);
CREATE INDEX IF NOT EXISTS idx_products_pos_category_id_fk ON public.products (pos_category_id);
CREATE INDEX IF NOT EXISTS idx_products_supplier_id_fk ON public.products (supplier_id);
CREATE INDEX IF NOT EXISTS idx_purchase_items_organisation_id_fk ON public.purchase_items (organisation_id);
CREATE INDEX IF NOT EXISTS idx_purchase_items_purchase_id_fk ON public.purchase_items (purchase_id);
CREATE INDEX IF NOT EXISTS idx_purchase_items_stock_item_id_fk ON public.purchase_items (stock_item_id);
CREATE INDEX IF NOT EXISTS idx_purchases_posted_by_fk ON public.purchases (posted_by);
CREATE INDEX IF NOT EXISTS idx_purchases_received_by_user_id_fk ON public.purchases (received_by_user_id);
CREATE INDEX IF NOT EXISTS idx_purchases_site_org_fk ON public.purchases (site_id, organisation_id);
CREATE INDEX IF NOT EXISTS idx_purchases_supplier_id_fk ON public.purchases (supplier_id);
CREATE INDEX IF NOT EXISTS idx_recipe_items_organisation_id_fk ON public.recipe_items (organisation_id);
CREATE INDEX IF NOT EXISTS idx_recipe_items_recipe_id_fk ON public.recipe_items (recipe_id);
CREATE INDEX IF NOT EXISTS idx_recipes_product_id_fk ON public.recipes (product_id);
CREATE INDEX IF NOT EXISTS idx_table_tab_items_kitchen_order_id_fk ON public.table_tab_items (kitchen_order_id);
CREATE INDEX IF NOT EXISTS idx_table_tab_items_product_id_fk ON public.table_tab_items (product_id);
CREATE INDEX IF NOT EXISTS idx_table_tab_items_settled_transaction_id_fk ON public.table_tab_items (settled_transaction_id);
CREATE INDEX IF NOT EXISTS idx_table_tab_items_site_id_fk ON public.table_tab_items (site_id);
CREATE INDEX IF NOT EXISTS idx_table_tabs_bill_requested_by_fk ON public.table_tabs (bill_requested_by);
CREATE INDEX IF NOT EXISTS idx_table_tabs_opened_by_fk ON public.table_tabs (opened_by);
CREATE INDEX IF NOT EXISTS idx_table_tabs_site_id_fk ON public.table_tabs (site_id);
