export type HelpStep = {
  title: string;
  body: string;
  screenshot?: string;
  titleRo?: string;
  bodyRo?: string;
};

export type HelpArticle = {
  slug: string;
  title: string;
  description: string;
  category: string;
  icon: string;
  steps: HelpStep[];
  relatedSlugs?: string[];
  titleRo?: string;
  descriptionRo?: string;
};

export type HelpCategory = {
  id: string;
  label: string;
  icon: string;
  description: string;
  labelRo?: string;
  descriptionRo?: string;
};

export const HELP_CATEGORIES: HelpCategory[] = [
  { id: "getting-started", label: "Getting started",    icon: "🚀", description: "Set up your account and get selling fast", labelRo: "Primii pași", descriptionRo: "Configurați-vă contul și începeți să vindeți rapid" },
  { id: "pos",             label: "POS & selling",      icon: "🛒", description: "Make sales, apply discounts, and take payments", labelRo: "Casă & vânzări", descriptionRo: "Realizați vânzări, aplicați reduceri și încasați plăți" },
  { id: "products",        label: "Products",           icon: "📦", description: "Add products, set prices, and manage your menu", labelRo: "Produse", descriptionRo: "Adăugați produse, setați prețuri și gestionați meniul" },
  { id: "stock",           label: "Stock & purchases",  icon: "📊", description: "Track stock levels and record supplier deliveries", labelRo: "Stoc & achiziții", descriptionRo: "Urmăriți nivelurile de stoc și înregistrați recepțiile de la furnizori" },
  { id: "reports",         label: "Reports",            icon: "📈", description: "Daily Z-reports, sales summaries, and VAT breakdowns", labelRo: "Rapoarte", descriptionRo: "Rapoarte Z zilnice, sumar vânzări și defalcare TVA" },
  { id: "recipes",         label: "Recipe costing",     icon: "🧾", description: "Link ingredients to dishes and see your margins", labelRo: "Cost rețete", descriptionRo: "Legați ingredientele de preparate și vedeți marjele" },
  { id: "settings",        label: "Settings",           icon: "⚙️",  description: "Manage your business, team, and billing", labelRo: "Setări", descriptionRo: "Gestionați afacerea, echipa și facturarea" },
  { id: "romania",         label: "Romania & FiscalNet", icon: "🇷🇴", description: "FiscalNet fiscal receipts, TVA rates, and lei/RON setup for Romanian businesses", labelRo: "România & FiscalNet", descriptionRo: "Bonuri fiscale prin FiscalNet, cote TVA și configurare lei/RON pentru afaceri din România" },
];

export const HELP_ARTICLES: HelpArticle[] = [
  {
    slug: "setup-your-account",
    title: "Set up your account",
    titleRo: "Configurați-vă contul",
    description: "Complete the setup checklist to get your business ready to sell in minutes.",
    descriptionRo: "Parcurgeți lista de configurare pentru a fi gata de vânzare în câteva minute.",
    category: "getting-started",
    icon: "🚀",
    steps: [
      { title: "Open the Setup guide", body: "After logging in, click **Setup guide** in the left sidebar. The checklist adapts to your business level: small shops see a POS-first path; restaurants also see stock and recipe steps when those modules are enabled.", screenshot: "setup-checklist.png",
        titleRo: "Deschideți Ghidul de configurare", bodyRo: "După autentificare, apăsați **Ghid de configurare** din bara laterală. Lista se adaptează la tipul afacerii: magazinele mici văd un traseu axat pe casă; restaurantele văd și pași de stoc și rețete când acele module sunt activate." },
      { title: "Add your business details", body: "Enter your business name, currency, and timezone. These appear on reports and receipts.", screenshot: "settings.png",
        titleRo: "Adăugați detaliile afacerii", bodyRo: "Introduceți numele afacerii, moneda și fusul orar. Acestea apar pe rapoarte și bonuri." },
      { title: "Add your first product", body: "Go to **Products → New product**. Give it a name, set the selling price, and choose a category. Click Save.", screenshot: "products-new.png",
        titleRo: "Adăugați primul produs", bodyRo: "Mergeți la **Produse → Produs nou**. Dați-i un nume, setați prețul de vânzare și alegeți o categorie. Apăsați Salvează." },
      { title: "Open the POS and make a test sale", body: "Click **POS** in the sidebar. Tap a product to add it to the cart, then press **Charge**. Your setup is complete.", screenshot: "pos-with-items.png",
        titleRo: "Deschideți casa și faceți o vânzare de test", bodyRo: "Apăsați **POS** din bara laterală. Atingeți un produs pentru a-l adăuga în coș, apoi apăsați **Încasează**. Configurarea este completă." },
    ],
    relatedSlugs: ["make-a-sale", "add-a-product"],
  },
  {
    slug: "first-15-minutes-checklist",
    title: "First 15 minutes checklist",
    titleRo: "Lista de verificare — primele 15 minute",
    description: "The fastest path from signup to a working first sale.",
    descriptionRo: "Cel mai rapid traseu de la înregistrare la prima vânzare funcțională.",
    category: "getting-started",
    icon: "✅",
    steps: [
      { title: "Add business details", body: "Open **Settings** and confirm the business name, country, currency, and receipt details. If you chose a simple shop profile at signup, stock and recipe steps stay hidden until you enable them under **Settings → Modules**.",
        titleRo: "Adăugați detaliile afacerii", bodyRo: "Deschideți **Setări** și confirmați numele afacerii, țara, moneda și detaliile de pe bon. Dacă ați ales un profil simplu de magazin la înregistrare, pașii de stoc și rețete rămân ascunși până le activați din **Setări → Module**." },
      { title: "Add your first 5 products", body: "Open **Products** and add the most common items you sell. Keep it simple: name, category, selling price, and POS visibility.",
        titleRo: "Adăugați primele 5 produse", bodyRo: "Deschideți **Produse** și adăugați articolele cele mai vândute. Păstrați-o simplu: nume, categorie, preț de vânzare și vizibilitate în POS." },
      { title: "Check payment methods", body: "Open **Settings** and make sure Cash and Card are available. Add other methods only if you really use them.",
        titleRo: "Verificați metodele de plată", bodyRo: "Deschideți **Setări** și asigurați-vă că Numerar și Card sunt disponibile. Adăugați alte metode doar dacă chiar le folosiți." },
      { title: "Open the till", body: "Open **POS**, enter the opening cash float, and start the session.",
        titleRo: "Deschideți casa", bodyRo: "Deschideți **POS**, introduceți numerarul de deschidere și porniți sesiunea." },
      { title: "Make a test sale", body: "Add one product to the cart, choose a payment method, and press **Charge**.",
        titleRo: "Faceți o vânzare de test", bodyRo: "Adăugați un produs în coș, alegeți o metodă de plată și apăsați **Încasează**." },
      { title: "Check the daily report", body: "Open **Reports** and confirm the sale, payment method, and total are visible.",
        titleRo: "Verificați raportul zilnic", bodyRo: "Deschideți **Rapoarte** și confirmați că vânzarea, metoda de plată și totalul sunt vizibile." },
    ],
    relatedSlugs: ["setup-your-account", "make-a-sale", "sales-report"],
  },
  {
    slug: "first-day-checklist",
    title: "First day checklist",
    titleRo: "Lista de verificare — prima zi",
    description: "What to do on the first real trading day.",
    descriptionRo: "Ce trebuie făcut în prima zi reală de activitate.",
    category: "getting-started",
    icon: "📅",
    steps: [
      { title: "Add main products", body: "Add the products your staff sell most often. Leave slow-moving or special items until later.",
        titleRo: "Adăugați produsele principale", bodyRo: "Adăugați produsele pe care personalul le vinde cel mai des. Lăsați articolele speciale sau cu vânzare lentă pentru mai târziu." },
      { title: "Create clear categories", body: "Use simple categories such as Drinks, Food, Snacks, Retail, or Services.",
        titleRo: "Creați categorii clare", bodyRo: "Folosiți categorii simple, precum Băuturi, Mâncare, Gustări, Produse sau Servicii." },
      { title: "Train one staff member", body: "Show them how to open POS, add products, choose Cash or Card, and complete a sale.",
        titleRo: "Instruiți un membru al echipei", bodyRo: "Arătați-i cum să deschidă POS-ul, să adauge produse, să aleagă Numerar sau Card și să finalizeze o vânzare." },
      { title: "Record real sales", body: "Use franchisetech for normal sales during the day. Do not mix test sales with real sales unless you clearly void them.",
        titleRo: "Înregistrați vânzări reale", bodyRo: "Folosiți franchisetech pentru vânzările normale din timpul zilei. Nu amestecați vânzările de test cu cele reale decât dacă le anulați clar." },
      { title: "Compare cash/card totals", body: "At the end of the day, compare the report totals with your drawer and card terminal totals.",
        titleRo: "Comparați totalurile numerar/card", bodyRo: "La finalul zilei, comparați totalurile din raport cu sertarul de numerar și cu terminalul de card." },
      { title: "Review the report", body: "Check sales total, transaction count, payment method split, and top products.",
        titleRo: "Verificați raportul", bodyRo: "Verificați totalul vânzărilor, numărul de tranzacții, împărțirea pe metode de plată și produsele cele mai vândute." },
    ],
    relatedSlugs: ["make-a-sale", "sales-report", "reading-your-z-report"],
  },
  {
    slug: "first-week-checklist",
    title: "First week checklist",
    titleRo: "Lista de verificare — prima săptămână",
    description: "Use the first week to clean setup and decide what matters next.",
    descriptionRo: "Folosiți prima săptămână pentru a curăța configurarea și a decide ce urmează.",
    category: "getting-started",
    icon: "🗓️",
    steps: [
      { title: "Review top products", body: "Open **Reports** and check which products sell most often.",
        titleRo: "Verificați produsele de top", bodyRo: "Deschideți **Rapoarte** și verificați care produse se vând cel mai des." },
      { title: "Check sales by day", body: "Look for busy and quiet days so you understand the trading pattern.",
        titleRo: "Verificați vânzările pe zile", bodyRo: "Identificați zilele aglomerate și cele liniștite, ca să înțelegeți tiparul de activitate." },
      { title: "Clean the product list", body: "Rename unclear products, remove duplicates, and put products into the right categories.",
        titleRo: "Curățați lista de produse", bodyRo: "Redenumiți produsele neclare, eliminați duplicatele și puneți produsele în categoriile corecte." },
      { title: "Decide on stock and recipes", body: "If margins or stock control matter now, start the stock/margin checklist. If not, keep selling first.",
        titleRo: "Decideți asupra stocului și rețetelor", bodyRo: "Dacă marjele sau controlul stocului contează deja, începeți lista de verificare pentru stoc/marjă. Dacă nu, concentrați-vă întâi pe vânzare." },
      { title: "Choose a plan", body: "Open **Billing** and choose Core or Operations before the trial ends.",
        titleRo: "Alegeți un plan", bodyRo: "Deschideți **Facturare** și alegeți Core sau Operations înainte de finalul perioadei de probă." },
    ],
    relatedSlugs: ["manage-stock-levels", "recipe-costing-intro", "manage-settings"],
  },
  {
    slug: "stock-margin-checklist",
    title: "Stock and margin checklist",
    titleRo: "Lista de verificare — stoc și marjă",
    description: "Add ingredients, suppliers, purchases, and recipes when you are ready to track cost.",
    descriptionRo: "Adăugați ingrediente, furnizori, achiziții și rețete când sunteți gata să urmăriți costul.",
    category: "recipes",
    icon: "📊",
    steps: [
      { title: "Add ingredients", body: "Add stock items you buy, such as milk, coffee beans, chicken, packaging, or bottles.",
        titleRo: "Adăugați ingrediente", bodyRo: "Adăugați articolele de stoc pe care le cumpărați — lapte, boabe de cafea, pui, ambalaje sau sticle." },
      { title: "Add suppliers", body: "Add the suppliers you buy from most often.",
        titleRo: "Adăugați furnizori", bodyRo: "Adăugați furnizorii de la care cumpărați cel mai des." },
      { title: "Record a purchase", body: "Record what arrived, quantity, unit, and cost. This updates stock and cost information.",
        titleRo: "Înregistrați o achiziție", bodyRo: "Înregistrați ce a sosit, cantitatea, unitatea și costul. Aceasta actualizează stocul și informațiile de cost." },
      { title: "Create a recipe", body: "Connect a sellable product to the ingredients used for one portion.",
        titleRo: "Creați o rețetă", bodyRo: "Legați un produs vandabil de ingredientele folosite pentru o porție." },
      { title: "Check margin", body: "Open **Reports → Margins** to review cost, selling price, and margin.",
        titleRo: "Verificați marja", bodyRo: "Deschideți **Rapoarte → Marje** pentru a revizui costul, prețul de vânzare și marja." },
    ],
    relatedSlugs: ["add-an-ingredient", "record-a-purchase", "recipe-costing-intro"],
  },
  {
    slug: "owner-daily-checklist",
    title: "Owner daily checklist",
    titleRo: "Lista zilnică pentru proprietar",
    description: "The numbers an owner should check every trading day.",
    descriptionRo: "Cifrele pe care un proprietar ar trebui să le verifice în fiecare zi de activitate.",
    category: "reports",
    icon: "👤",
    steps: [
      { title: "Open the dashboard", body: "Start with today's sales, expected cash, and top products.",
        titleRo: "Deschideți panoul", bodyRo: "Începeți cu vânzările de azi, numerarul așteptat și produsele de top." },
      { title: "Check cash and card totals", body: "Compare franchisetech totals with the drawer and card terminal.",
        titleRo: "Verificați totalurile numerar și card", bodyRo: "Comparați totalurile din franchisetech cu sertarul și terminalul de card." },
      { title: "Check top products", body: "Look for best sellers and unusual gaps.",
        titleRo: "Verificați produsele de top", bodyRo: "Urmăriți cele mai vândute produse și eventualele goluri neobișnuite." },
      { title: "Review refunds or voids", body: "Check any failed, voided, or refunded items so mistakes are caught early.",
        titleRo: "Verificați rambursările sau anulările", bodyRo: "Verificați articolele eșuate, anulate sau rambursate, ca greșelile să fie observate din timp." },
      { title: "Close the till", body: "Count cash, enter counted cash, add notes if needed, and close the session.",
        titleRo: "Închideți casa", bodyRo: "Numărați numerarul, introduceți suma numărată, adăugați observații dacă e nevoie și închideți sesiunea." },
    ],
    relatedSlugs: ["dashboard-overview", "sales-report", "reading-your-z-report"],
  },
  {
    slug: "staff-cashier-checklist",
    title: "Staff and cashier checklist",
    titleRo: "Lista de verificare pentru personal și casieri",
    description: "A short checklist for anyone using the till.",
    descriptionRo: "O listă scurtă pentru oricine folosește casa.",
    category: "pos",
    icon: "🧑‍💼",
    steps: [
      { title: "Log in", body: "Use your own account so sales and actions are traceable.",
        titleRo: "Autentificați-vă", bodyRo: "Folosiți propriul cont, ca vânzările și acțiunile să poată fi urmărite." },
      { title: "Select products", body: "Tap the products the customer wants and check quantities before charging.",
        titleRo: "Selectați produsele", bodyRo: "Atingeți produsele cerute de client și verificați cantitățile înainte de încasare." },
      { title: "Apply discount only if allowed", body: "Only apply a discount when the manager or owner has approved it.",
        titleRo: "Aplicați reducerea doar dacă este permisă", bodyRo: "Aplicați o reducere doar când managerul sau proprietarul a aprobat-o." },
      { title: "Take payment", body: "Choose the right payment method: Cash, Card, Online, or Other.",
        titleRo: "Încasați plata", bodyRo: "Alegeți metoda de plată corectă: Numerar, Card, Online sau Altele." },
      { title: "Give receipt if needed", body: "Open the receipt after sale completion if the customer asks.",
        titleRo: "Oferiți bonul dacă este cerut", bodyRo: "Deschideți bonul după finalizarea vânzării dacă clientul îl cere." },
      { title: "Call a manager for refunds", body: "If a sale needs refunding or voiding, ask the manager unless you have permission.",
        titleRo: "Apelați un manager pentru rambursări", bodyRo: "Dacă o vânzare trebuie rambursată sau anulată, cereți managerul, dacă nu aveți permisiune." },
    ],
    relatedSlugs: ["make-a-sale", "manage-settings"],
  },
  {
    slug: "dashboard-overview",
    title: "Understanding your dashboard",
    titleRo: "Înțelegerea panoului",
    description: "See today's revenue, top products, and next steps at a glance.",
    descriptionRo: "Vedeți dintr-o privire încasările de azi, produsele de top și pașii următori.",
    category: "getting-started",
    icon: "📊",
    steps: [
      { title: "View your daily summary", body: "The dashboard shows **Sales**, **Expected cash**, and **Top product** for today. Switch between Today / This week / This month using the buttons at the top right.", screenshot: "dashboard-overview.png",
        titleRo: "Vedeți sumarul zilnic", bodyRo: "Panoul arată **Vânzări**, **Numerar așteptat** și **Produs de top** pentru ziua curentă. Comutați între Azi / Săptămâna aceasta / Luna aceasta din butoanele din dreapta sus." },
      { title: "Next best action", body: "The **Next best action** panel suggests what to do next — add products, manage stock, create a recipe — so you always know where to focus.", screenshot: "dashboard-overview.png",
        titleRo: "Următorul pas recomandat", bodyRo: "Panoul **Următorul pas recomandat** sugerează ce e de făcut — adăugați produse, gestionați stocul, creați o rețetă — ca să știți mereu unde să vă concentrați." },
      { title: "Quick links", body: "Use the Reports shortcuts at the bottom to jump straight to Sales, Till closes, VAT, and Margins without navigating the sidebar.", screenshot: "dashboard-overview.png",
        titleRo: "Scurtături", bodyRo: "Folosiți scurtăturile de Rapoarte din partea de jos pentru a ajunge direct la Vânzări, Închideri de casă, TVA și Marje, fără a naviga prin bara laterală." },
    ],
    relatedSlugs: ["reading-your-z-report", "sales-report"],
  },
  {
    slug: "make-a-sale",
    title: "Make a sale",
    titleRo: "Realizați o vânzare",
    description: "Add items to the cart, apply discounts, and take payment.",
    descriptionRo: "Adăugați articole în coș, aplicați reduceri și încasați plata.",
    category: "pos",
    icon: "🛒",
    steps: [
      { title: "Open the POS", body: "Click **POS** in the left sidebar. You will see your product grid on the left and the cart on the right.", screenshot: "pos-empty.png",
        titleRo: "Deschideți POS-ul", bodyRo: "Apăsați **POS** din bara laterală. Veți vedea grila de produse în stânga și coșul în dreapta." },
      { title: "Add items to the cart", body: "Tap any product tile to add it to the cart. Tap again to increase the quantity, or use the **+** / **−** buttons next to each cart line.", screenshot: "pos-with-items.png",
        titleRo: "Adăugați articole în coș", bodyRo: "Atingeți orice produs pentru a-l adăuga în coș. Atingeți din nou pentru a crește cantitatea, sau folosiți butoanele **+** / **−** de lângă fiecare linie din coș." },
      { title: "Apply a discount (optional)", body: "Tap **Discount** below the cart total. Enter a percentage (e.g. 10%) or a fixed amount. The total updates immediately.", screenshot: "pos-with-items.png",
        titleRo: "Aplicați o reducere (opțional)", bodyRo: "Atingeți **Reducere** sub totalul coșului. Introduceți un procent (de ex. 10%) sau o sumă fixă. Totalul se actualizează imediat." },
      { title: "Charge the customer", body: "Press the blue **Charge €X.XX** button. Select the payment method — Cash, Card, or Other — then confirm. The sale is recorded and stock is deducted automatically.", screenshot: "pos-with-items.png",
        titleRo: "Încasați clientul", bodyRo: "Apăsați butonul albastru **Încasează X,XX lei**. Selectați metoda de plată — Numerar, Card sau Altele — apoi confirmați. Vânzarea este înregistrată, iar stocul este scăzut automat." },
      { title: "Add a customer name (optional)", body: "Tap the customer field at the top of the cart and type a name or order number. Useful for click-and-collect or identifying a sale.", screenshot: "pos-with-items.png",
        titleRo: "Adăugați numele clientului (opțional)", bodyRo: "Atingeți câmpul de client din partea de sus a coșului și introduceți un nume sau un număr de comandă. Util pentru comenzi de ridicat sau pentru identificarea unei vânzări." },
    ],
    relatedSlugs: ["reading-your-z-report", "setup-your-account"],
  },
  {
    slug: "add-a-product",
    title: "Add a product",
    titleRo: "Adăugați un produs",
    description: "Create a new product with a name, price, and category.",
    descriptionRo: "Creați un produs nou cu nume, preț și categorie.",
    category: "products",
    icon: "📦",
    steps: [
      { title: "Go to Products", body: "Click **Products** in the sidebar to see your product list.", screenshot: "products-list.png",
        titleRo: "Mergeți la Produse", bodyRo: "Apăsați **Produse** din bara laterală pentru a vedea lista de produse." },
      { title: "Click New product", body: "Press the **New product** button at the top right.", screenshot: "products-list.png",
        titleRo: "Apăsați Produs nou", bodyRo: "Apăsați butonul **Produs nou** din dreapta sus." },
      { title: "Fill in the details", body: "Enter the **Product name**, **Selling price** (inc. VAT), and choose a **Category**. Categories group products on the POS screen.", screenshot: "products-new.png",
        titleRo: "Completați detaliile", bodyRo: "Introduceți **Numele produsului**, **Prețul de vânzare** (cu TVA inclus) și alegeți o **Categorie**. Categoriile grupează produsele pe ecranul POS." },
      { title: "Enable stock tracking (optional)", body: "Toggle **Track stock** if you want the app to deduct one unit each time this product is sold. Set an initial **Stock on hand** quantity.", screenshot: "products-new.png",
        titleRo: "Activați urmărirea stocului (opțional)", bodyRo: "Activați **Urmărește stocul** dacă doriți ca aplicația să scadă o unitate de fiecare dată când produsul este vândut. Setați o cantitate inițială de **Stoc disponibil**." },
      { title: "Save", body: "Click **Save product**. The product appears on your POS immediately.", screenshot: "products-list.png",
        titleRo: "Salvați", bodyRo: "Apăsați **Salvează produsul**. Produsul apare imediat în POS." },
    ],
    relatedSlugs: ["manage-stock-levels", "recipe-costing-intro"],
  },
  {
    slug: "add-an-ingredient",
    title: "Add an ingredient",
    titleRo: "Adăugați un ingredient",
    description: "Track raw ingredients and their unit cost for recipe margin calculations.",
    descriptionRo: "Urmăriți materiile prime și costul lor unitar pentru calculul marjei rețetelor.",
    category: "products",
    icon: "🧂",
    steps: [
      { title: "Switch to Ingredients view", body: "Go to **Products** and click the **Ingredients** filter tab at the top.", screenshot: "ingredients-list.png",
        titleRo: "Comutați la vizualizarea Ingrediente", bodyRo: "Mergeți la **Produse** și apăsați fila de filtru **Ingrediente** din partea de sus." },
      { title: "Click New ingredient", body: "Press **New ingredient**. Enter the name (e.g. \"Oat milk\"), unit (litre, kg, unit), and unit cost.", screenshot: "ingredients-list.png",
        titleRo: "Apăsați Ingredient nou", bodyRo: "Apăsați **Ingredient nou**. Introduceți numele (de ex. „Lapte de ovăz”), unitatea (litru, kg, bucată) și costul unitar." },
      { title: "Set stock tracking", body: "Toggle **Track stock** and enter current quantity on hand. The app will deduct ingredient quantity each time a linked recipe product is sold.", screenshot: "ingredients-list.png",
        titleRo: "Setați urmărirea stocului", bodyRo: "Activați **Urmărește stocul** și introduceți cantitatea curentă disponibilă. Aplicația va scădea cantitatea de ingredient de fiecare dată când un produs cu rețetă asociată este vândut." },
      { title: "Save", body: "Click **Save ingredient**. You can now link this ingredient to a product recipe.", screenshot: "ingredients-list.png",
        titleRo: "Salvați", bodyRo: "Apăsați **Salvează ingredientul**. Acum îl puteți lega de rețeta unui produs." },
    ],
    relatedSlugs: ["recipe-costing-intro", "manage-stock-levels"],
  },
  {
    slug: "manage-stock-levels",
    title: "Manage stock levels",
    titleRo: "Gestionați nivelurile de stoc",
    description: "View current stock, adjust quantities, and spot items running low.",
    descriptionRo: "Vedeți stocul curent, ajustați cantitățile și identificați articolele pe cale să se termine.",
    category: "stock",
    icon: "📦",
    steps: [
      { title: "Open Stock", body: "Click **Stock levels** under the Inventory section in the sidebar.", screenshot: "stock-levels.png",
        titleRo: "Deschideți Stocul", bodyRo: "Apăsați **Niveluri stoc** din secțiunea Inventar a barei laterale." },
      { title: "Read the stock table", body: "Each row shows product name, category, **On hand** quantity, **Reorder point**, unit, and cost. Rows in red are below reorder threshold.", screenshot: "stock-levels.png",
        titleRo: "Citiți tabelul de stoc", bodyRo: "Fiecare rând arată numele produsului, categoria, cantitatea **Disponibil**, **Pragul de reaprovizionare**, unitatea și costul. Rândurile roșii sunt sub pragul de reaprovizionare." },
      { title: "Update a quantity inline", body: "Click any **On hand** number to edit it directly. Type the new quantity and press **Enter** (or click ✓). Saved immediately.", screenshot: "stock-levels.png",
        titleRo: "Actualizați o cantitate direct", bodyRo: "Apăsați orice cifră din **Disponibil** pentru a o edita direct. Introduceți noua cantitate și apăsați **Enter** (sau ✓). Se salvează imediat." },
      { title: "Filter by category", body: "Use the category filter at the top to focus on one group at a time — e.g. show only Ingredients.", screenshot: "stock-levels.png",
        titleRo: "Filtrați după categorie", bodyRo: "Folosiți filtrul de categorie din partea de sus pentru a vedea un singur grup — de exemplu, doar Ingrediente." },
    ],
    relatedSlugs: ["record-a-purchase", "add-a-product"],
  },
  {
    slug: "record-a-purchase",
    title: "Record a supplier purchase",
    titleRo: "Înregistrați o achiziție de la furnizor",
    description: "Log a delivery from a supplier to update stock and track purchasing costs.",
    descriptionRo: "Înregistrați o livrare de la un furnizor pentru a actualiza stocul și a urmări costurile de achiziție.",
    category: "stock",
    icon: "🚚",
    steps: [
      { title: "Go to Purchases", body: "Click **Purchases** under Inventory in the sidebar.", screenshot: "purchases.png",
        titleRo: "Mergeți la Achiziții", bodyRo: "Apăsați **Achiziții** din secțiunea Inventar a barei laterale." },
      { title: "Click New purchase", body: "Press **New purchase**. Select the supplier, set the delivery date, and add line items.", screenshot: "purchases.png",
        titleRo: "Apăsați Achiziție nouă", bodyRo: "Apăsați **Achiziție nouă**. Selectați furnizorul, setați data livrării și adăugați liniile." },
      { title: "Add line items", body: "For each item delivered, select the ingredient or product, enter quantity received and unit cost. The total calculates automatically.", screenshot: "purchases.png",
        titleRo: "Adăugați liniile", bodyRo: "Pentru fiecare articol livrat, selectați ingredientul sau produsul, introduceți cantitatea primită și costul unitar. Totalul se calculează automat." },
      { title: "Save the purchase", body: "Click **Save purchase**. Stock on hand is updated immediately for every item on the purchase.", screenshot: "purchases.png",
        titleRo: "Salvați achiziția", bodyRo: "Apăsați **Salvează achiziția**. Stocul disponibil se actualizează imediat pentru fiecare articol din achiziție." },
    ],
    relatedSlugs: ["manage-stock-levels"],
  },
  {
    slug: "sales-report",
    title: "Sales report",
    titleRo: "Raport de vânzări",
    description: "See gross sales, transaction count, and payment method breakdown for any date range.",
    descriptionRo: "Vedeți vânzările brute, numărul de tranzacții și defalcarea pe metode de plată pentru orice interval de date.",
    category: "reports",
    icon: "💶",
    steps: [
      { title: "Open Sales report", body: "Go to **Reports → Sales** in the sidebar.", screenshot: "reports-sales.png",
        titleRo: "Deschideți Raportul de vânzări", bodyRo: "Mergeți la **Rapoarte → Vânzări** din bara laterală." },
      { title: "Select a date range", body: "Use the date picker to choose Today, This week, This month, or a custom range.", screenshot: "reports-sales.png",
        titleRo: "Selectați un interval de date", bodyRo: "Folosiți selectorul de dată pentru a alege Azi, Săptămâna aceasta, Luna aceasta sau un interval personalizat." },
      { title: "Read the summary", body: "The top row shows **Gross sales**, **Net sales**, **VAT collected**, and **Transactions**. Below is a breakdown by payment method.", screenshot: "reports-sales.png",
        titleRo: "Citiți sumarul", bodyRo: "Rândul de sus arată **Vânzări brute**, **Vânzări nete**, **TVA colectat** și **Tranzacții**. Mai jos este o defalcare pe metode de plată." },
      { title: "See top products", body: "Scroll down to see your best-selling products ranked by revenue for the period.", screenshot: "reports-sales.png",
        titleRo: "Vedeți produsele de top", bodyRo: "Derulați în jos pentru a vedea produsele cele mai vândute, clasate după încasări pentru perioada respectivă." },
    ],
    relatedSlugs: ["reading-your-z-report", "vat-report"],
  },
  {
    slug: "reading-your-z-report",
    title: "Reading your Z-report",
    titleRo: "Citirea raportului Z",
    description: "The Z-report is your end-of-day till close summary — used to reconcile cash and verify takings.",
    descriptionRo: "Raportul Z este sumarul de închidere a casei la finalul zilei — folosit pentru a verifica numerarul și încasările.",
    category: "reports",
    icon: "🏁",
    steps: [
      { title: "Open the Z-report", body: "Go to **Reports → Till closes** in the sidebar.", screenshot: "reports-zreport.png",
        titleRo: "Deschideți raportul Z", bodyRo: "Mergeți la **Rapoarte → Închideri de casă** din bara laterală." },
      { title: "Select the date", body: "Use the date picker to choose any trading day. Each till close for that day is listed.", screenshot: "reports-zreport.png",
        titleRo: "Selectați data", bodyRo: "Folosiți selectorul de dată pentru a alege orice zi de activitate. Fiecare închidere de casă din acea zi este listată." },
      { title: "Check the totals", body: "The report shows **Total sales**, **Cash sales**, **Card sales**, **Refunds**, and **Net**. Compare Cash on hand against your physical cash to spot discrepancies.", screenshot: "reports-zreport.png",
        titleRo: "Verificați totalurile", bodyRo: "Raportul arată **Total vânzări**, **Vânzări numerar**, **Vânzări card**, **Rambursări** și **Net**. Comparați numerarul din sistem cu numerarul fizic pentru a depista diferențe." },
      { title: "Print or export", body: "Press **Print** (or save as PDF) to keep a copy for your records. Often required for VAT filing.", screenshot: "reports-zreport.png",
        titleRo: "Tipăriți sau exportați", bodyRo: "Apăsați **Tipărește** (sau salvați ca PDF) pentru a păstra o copie pentru evidențe. Adesea necesar pentru declarația de TVA." },
    ],
    relatedSlugs: ["sales-report", "vat-report"],
  },
  {
    slug: "vat-report",
    title: "VAT report",
    titleRo: "Raport TVA",
    description: "Net, VAT, and gross figures broken down by rate — ready for your accountant.",
    descriptionRo: "Sume nete, TVA și brute defalcate pe cotă — gata pentru contabil.",
    category: "reports",
    icon: "🧾",
    steps: [
      { title: "Open the VAT report", body: "Go to **Reports → VAT** in the sidebar.", screenshot: "reports-vat.png",
        titleRo: "Deschideți raportul TVA", bodyRo: "Mergeți la **Rapoarte → TVA** din bara laterală." },
      { title: "Select your filing period", body: "Choose the date range that matches your VAT period (bi-monthly in Ireland).", screenshot: "reports-vat.png",
        titleRo: "Selectați perioada de declarare", bodyRo: "Alegeți intervalul de date care corespunde perioadei dumneavoastră de TVA (de obicei lunar în România)." },
      { title: "Read the breakdown", body: "The report shows **Net**, **VAT**, and **Gross** for each rate (0%, 9%, 13.5%, 23%). The totals row is what you report to Revenue.", screenshot: "reports-vat.png",
        titleRo: "Citiți defalcarea", bodyRo: "Raportul arată **Net**, **TVA** și **Brut** pentru fiecare cotă (0%, 11%, 21%). Rândul de total este cel pe care îl declarați la ANAF." },
      { title: "Share with your accountant", body: "Export as CSV or print. Your accountant needs the Net and VAT columns to complete your VAT return.", screenshot: "reports-vat.png",
        titleRo: "Trimiteți-l contabilului", bodyRo: "Exportați ca CSV sau tipăriți. Contabilul are nevoie de coloanele Net și TVA pentru a completa decontul de TVA." },
    ],
    relatedSlugs: ["sales-report", "reading-your-z-report"],
  },
  {
    slug: "recipe-costing-intro",
    title: "Set up recipe costing",
    titleRo: "Configurați costul rețetelor",
    description: "Link ingredients to a product to calculate cost, margin, and how many you can make.",
    descriptionRo: "Legați ingredientele de un produs pentru a calcula costul, marja și câte porții puteți face.",
    category: "recipes",
    icon: "🧾",
    steps: [
      { title: "Add your ingredients first", body: "Before creating a recipe, make sure each ingredient exists in **Products → Ingredients** with a unit cost set.", screenshot: "ingredients-list.png",
        titleRo: "Adăugați mai întâi ingredientele", bodyRo: "Înainte de a crea o rețetă, asigurați-vă că fiecare ingredient există în **Produse → Ingrediente** cu un cost unitar setat." },
      { title: "Open the product to add a recipe to", body: "Go to **Products**, find the product (e.g. \"Flat White\"), and click it to open the edit view.", screenshot: "products-list.png",
        titleRo: "Deschideți produsul pentru a-i adăuga o rețetă", bodyRo: "Mergeți la **Produse**, găsiți produsul (de ex. „Flat White”) și apăsați-l pentru a deschide vizualizarea de editare." },
      { title: "Add recipe lines", body: "In the **Recipe** section, click **Add ingredient**. Select the ingredient and enter the quantity used per serving.", screenshot: "ingredients-list.png",
        titleRo: "Adăugați liniile rețetei", bodyRo: "În secțiunea **Rețetă**, apăsați **Adaugă ingredient**. Selectați ingredientul și introduceți cantitatea folosită per porție." },
      { title: "Read the margin summary", body: "The recipe panel shows **Cost per portion**, **Margin %**, and **Portions available** based on current stock. Adjust price or reduce waste to improve margins.", screenshot: "reports-margins.png",
        titleRo: "Citiți sumarul marjei", bodyRo: "Panoul rețetei arată **Cost per porție**, **Marjă %** și **Porții disponibile** pe baza stocului curent. Ajustați prețul sau reduceți risipa pentru a îmbunătăți marjele." },
    ],
    relatedSlugs: ["add-an-ingredient", "manage-stock-levels"],
  },
  {
    slug: "romania-fiscalnet-setup",
    title: "Romania setup: FiscalNet, TVA, and fiscal receipts",
    titleRo: "Configurare România: FiscalNet, TVA și bonuri fiscale",
    description: "Configure franchisetech for Romanian organisations — FiscalNet fiscal receipts, TVA rates, lei/RON, and owner checklist before go-live.",
    descriptionRo: "Configurați franchisetech pentru organizații din România — bonuri fiscale prin FiscalNet, cote TVA, lei/RON și lista proprietarului înainte de lansare.",
    category: "romania",
    icon: "🇷🇴",
    steps: [
      {
        title: "Who this guide is for",
        titleRo: "Pentru cine este acest ghid",
        body: "This guide is for business owners operating in Romania who want to issue fiscal receipts through FiscalNet via franchisetech. You will need a FiscalNet provider (fiscal printer or cloud fiscal service) and your accountant's sign-off before going live.",
        bodyRo: "Acest ghid este pentru proprietari de afaceri din România care vor să emită bonuri fiscale prin FiscalNet, din franchisetech. Aveți nevoie de un furnizor FiscalNet (imprimantă fiscală sau serviciu fiscal cloud) și de acordul contabilului înainte de lansare.",
      },
      {
        title: "Enable Romania settings in your account",
        titleRo: "Activați setările pentru România în cont",
        body: "Go to **Settings → Business**. Set your **Currency** to RON (lei) and your **Country** to Romania. This unlocks Romanian TVA rates and the FiscalNet configuration section.",
        bodyRo: "Mergeți la **Setări → Afacere**. Setați **Moneda** la RON (lei) și **Țara** la România. Aceasta deblochează cotele TVA românești și secțiunea de configurare FiscalNet.",
        screenshot: "settings.png",
      },
      {
        title: "Set your TVA rates on products",
        titleRo: "Setați cotele TVA pe produse",
        body: "Romanian TVA rates — 21% (standard), 11% (food/hospitality), and 0% (exempt) — are pre-loaded. Go to **Products**, edit each product, and assign the correct TVA rate. Your accountant can confirm which rate applies to each product type.",
        bodyRo: "Cotele TVA românești — 21% (standard), 11% (alimentație/HoReCa) și 0% (scutit) — sunt precărcate. Mergeți la **Produse**, editați fiecare produs și atribuiți cota TVA corectă. Contabilul poate confirma ce cotă se aplică fiecărui tip de produs.",
        screenshot: "products-new.png",
      },
      {
        title: "Configure FiscalNet",
        titleRo: "Configurați FiscalNet",
        body: "Go to **Settings → FiscalNet**. Enter your FiscalNet provider credentials (CIF, serial number, and API token) supplied by your fiscal printer or cloud fiscal service provider. Do not use live credentials for test transactions.",
        bodyRo: "Mergeți la **Setări → FiscalNet**. Introduceți datele de acces FiscalNet (CIF, serie și token API) furnizate de imprimanta fiscală sau de serviciul fiscal cloud. Nu folosiți datele de acces live pentru tranzacții de test.",
        screenshot: "settings.png",
      },
      {
        title: "Map payment types to FiscalNet codes",
        titleRo: "Mapați metodele de plată la codurile FiscalNet",
        body: "FiscalNet requires a payment type code for every transaction. Payment types mapped for FiscalNet (codes 1–8): **1 = cash, 2 = card, 3 = credit, 4 = tichete masă, 5 = tichete valorice, 6 = voucher, 7 = plată modernă**. Review the mapping in **Settings → FiscalNet → Payment mapping** and adjust if your provider requires a different mapping.",
        bodyRo: "FiscalNet cere un cod de tip de plată pentru fiecare tranzacție. Metodele mapate pentru FiscalNet (coduri 1–8): **1 = numerar, 2 = card, 3 = credit, 4 = tichete masă, 5 = tichete valorice, 6 = voucher, 7 = plată modernă**. Verificați maparea din **Setări → FiscalNet → Mapare plăți** și ajustați-o dacă furnizorul cere altă mapare.",
        screenshot: "settings.png",
      },
      {
        title: "Test with your fiscal provider before go-live",
        titleRo: "Testați cu furnizorul fiscal înainte de lansare",
        body: "Use the **Test fiscal receipt** button in **Settings → FiscalNet** to send a test transaction to your fiscal provider. Confirm the test receipt prints or is logged correctly. Do not go live until your provider and accountant have verified the setup.",
        bodyRo: "Folosiți butonul **Testează bon fiscal** din **Setări → FiscalNet** pentru a trimite o tranzacție de test către furnizorul fiscal. Confirmați că bonul de test se tipărește sau se înregistrează corect. Nu lansați live până ce furnizorul și contabilul nu au verificat configurarea.",
      },
      {
        title: "Owner checklist before go-live",
        titleRo: "Lista proprietarului înainte de lansare",
        body: "Before taking your first real fiscal sale:\n\n✅ FiscalNet credentials entered and verified\n✅ All products assigned the correct TVA rate\n✅ Payment type mapping reviewed\n✅ Test receipt confirmed with your fiscal provider\n✅ Accountant has reviewed the configuration\n✅ Backup cash/card process agreed in case of FiscalNet downtime",
        bodyRo: "Înainte de prima vânzare fiscală reală:\n\n✅ Datele de acces FiscalNet introduse și verificate\n✅ Toate produsele au cota TVA corectă atribuită\n✅ Maparea metodelor de plată verificată\n✅ Bon de test confirmat cu furnizorul fiscal\n✅ Contabilul a revizuit configurarea\n✅ Un proces de rezervă pentru numerar/card stabilit, în caz de indisponibilitate FiscalNet",
      },
      {
        title: "Daily reconciliation with the Z-report",
        titleRo: "Verificarea zilnică prin raportul Z",
        body: "At the end of each trading day, go to **Reports → Till closes** and run the Z-report. This shows daily totals by payment method and TVA rate. Keep a copy for your records — your accountant or fiscal advisor may need it for periodic filings.",
        bodyRo: "La finalul fiecărei zile de activitate, mergeți la **Rapoarte → Închideri de casă** și generați raportul Z. Acesta arată totalurile zilnice pe metodă de plată și cotă TVA. Păstrați o copie pentru evidențe — contabilul sau consultantul fiscal poate avea nevoie de ea pentru declarații periodice.",
        screenshot: "reports-zreport.png",
      },
      {
        title: "What franchisetech does not do",
        titleRo: "Ce nu face franchisetech",
        body: "franchisetech supports the fiscal receipt workflow through FiscalNet. It does not replace advice from a Romanian accountant, tax advisor, or fiscal printer provider. Businesses remain responsible for their own legal, fiscal, and accountant review. If in doubt about compliance, consult a qualified Romanian accountant.",
        bodyRo: "franchisetech susține fluxul de bonuri fiscale prin FiscalNet. Nu înlocuiește consultanța unui contabil, consultant fiscal sau furnizor de imprimante fiscale din România. Afacerile rămân responsabile pentru propria verificare legală, fiscală și contabilă. În caz de îndoială privind conformitatea, consultați un contabil autorizat.",
      },
    ],
    relatedSlugs: ["reading-your-z-report", "vat-report", "manage-settings"],
  },
  {
    slug: "manage-settings",
    title: "Manage your settings",
    titleRo: "Gestionați setările",
    description: "Update your business name, invite team members, and manage your subscription.",
    descriptionRo: "Actualizați numele afacerii, invitați membri ai echipei și gestionați abonamentul.",
    category: "settings",
    icon: "⚙️",
    steps: [
      { title: "Open Settings", body: "Click **Settings** at the bottom of the sidebar.", screenshot: "settings.png",
        titleRo: "Deschideți Setările", bodyRo: "Apăsați **Setări** din partea de jos a barei laterale." },
      { title: "Update business details", body: "Change your business name, contact email, or VAT number in the **Business** section. Press **Save** to apply.", screenshot: "settings.png",
        titleRo: "Actualizați detaliile afacerii", bodyRo: "Schimbați numele afacerii, emailul de contact sau CUI-ul în secțiunea **Afacere**. Apăsați **Salvează** pentru a aplica." },
      { title: "Invite a team member", body: "Go to the **Team** tab. Enter an email and assign the **Staff** role (POS only) or **Manager** role (full access).", screenshot: "settings.png",
        titleRo: "Invitați un membru al echipei", bodyRo: "Mergeți la fila **Echipă**. Introduceți un email și atribuiți rolul **Personal** (doar POS) sau **Manager** (acces complet)." },
      { title: "Manage your subscription", body: "The **Billing** tab shows your current plan, renewal date, and a link to update payment method or cancel.", screenshot: "settings.png",
        titleRo: "Gestionați abonamentul", bodyRo: "Fila **Facturare** arată planul curent, data de reînnoire și un link pentru a actualiza metoda de plată sau a anula." },
    ],
    relatedSlugs: ["setup-your-account"],
  },
  {
    slug: "loyalty-program-setup",
    title: "Set up the loyalty program",
    titleRo: "Configurați programul de fidelizare",
    description: "Turn on the phone-based stamp card, configure the reward, and see regulars who haven't been back.",
    descriptionRo: "Activați cardul de ștampile pe numărul de telefon, configurați recompensa și vedeți clienții fideli care nu au mai venit.",
    category: "settings",
    icon: "🎁",
    steps: [
      { title: "Enable the module", body: "Open [Settings → Integrations](/app/settings?tab=integrations) and find the **Program de fidelizare** card in the Marketplace. Click **Activează**. It's included in the Operations plan, and available as a paid add-on on Starter.", screenshot: "loyalty-marketplace.png",
        titleRo: "Activați modulul", bodyRo: "Deschideți [Setări → Integrări](/app/settings?tab=integrations) și găsiți cardul **Program de fidelizare** din Marketplace. Apăsați **Activează**. Este inclus în planul Operations și disponibil ca add-on plătit pe Starter." },
      { title: "Configure the reward", body: "Open [Loyalty settings](/app/settings/loyalty). Choose how many stamps earn a reward (3–20), pick **Discount fix** (a fixed lei amount off the total) or **Produs gratuit** (a free item, applied manually by the cashier), then set the thresholds for the regulars-at-risk panel — minimum visits and days of absence. Click **Salvează**.", screenshot: "loyalty-settings.png",
        titleRo: "Configurați recompensa", bodyRo: "Deschideți [Setări fidelizare](/app/settings/loyalty). Alegeți câte ștampile aduc o recompensă (3–20), alegeți **Discount fix** (o sumă fixă în lei scăzută din total) sau **Produs gratuit** (aplicat manual de casier), apoi setați pragurile pentru panoul de clienți fideli în risc — vizite minime și zile de absență. Apăsați **Salvează**." },
      { title: "How it works at checkout", body: "In [POS](/app/pos), select the customer as usual. A **Fidelizare** panel appears showing stamp progress. Every completed sale adds a stamp automatically — nothing extra for staff to do. Once the reward is ready, tap it to apply the discount; tap again to undo it before charging.", screenshot: "loyalty-pos-reward.png",
        titleRo: "Cum funcționează la casă", bodyRo: "În [POS](/app/pos), selectați clientul ca de obicei. Apare un panou **Fidelizare** care arată progresul ștampilelor. Fiecare vânzare finalizată adaugă automat o ștampilă — nimic în plus pentru personal. Când recompensa e gata, atingeți-o pentru a aplica reducerea; atingeți din nou pentru a o anula înainte de încasare." },
      { title: "See who's drifting away", body: "Open [Customers](/app/customers). The **Clienți fideli care nu au mai venit** panel lists regulars who used to visit often but haven't been seen recently, ranked by how much they've spent — useful for a personal follow-up.", screenshot: "loyalty-customers.png",
        titleRo: "Vedeți cine s-a îndepărtat", bodyRo: "Deschideți [Clienți](/app/customers). Panoul **Clienți fideli care nu au mai venit** listează clienții obișnuiți care veneau des dar nu au mai fost văzuți recent, ordonați după cât au cheltuit — util pentru o urmărire personală." },
    ],
    relatedSlugs: ["make-a-sale", "manage-settings"],
  },
];

export function getArticlesByCategory(categoryId: string): HelpArticle[] {
  return HELP_ARTICLES.filter((a) => a.category === categoryId);
}

export function getArticle(slug: string): HelpArticle | undefined {
  return HELP_ARTICLES.find((a) => a.slug === slug);
}
